package cn.earlymorning.netvideo.dao;

import cn.earlymorning.netvideo.beans.Course;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @author 63299
 * @ccreate 2019-05-12
 */
public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_course
     *
     * @mbg.generated
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_course
     *
     * @mbg.generated
     */
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_course
     *
     * @mbg.generated
     */
    Course selectByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Course record);

    List<Course> getCourses();

    List<Course> getCoursesByTypeId(@Param("typeId") Integer typeId);

    List<Course> search(@Param("q")String q);

    List<Course> getCoursesByName(@Param("courseName") String courseName);
}