package cn.earlymorning.netvideo.dao;

import cn.earlymorning.netvideo.beans.CourseType;

import java.util.List;

public interface CourseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course_type
     *
     * @mbg.generated
     */
    int insert(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course_type
     *
     * @mbg.generated
     */
    int insertSelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course_type
     *
     * @mbg.generated
     */
    CourseType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CourseType record);

    List<CourseType> getCourseTypes();


}