package cn.earlymorning.netvideo.dao;

import cn.earlymorning.netvideo.beans.Profession;

/**
 * @author 63299
 */
public interface ProfessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_profession
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_profession
     *
     * @mbg.generated
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_profession
     *
     * @mbg.generated
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_profession
     *
     * @mbg.generated
     */
    Profession selectByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_profession
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Profession record);
}