package cn.earlymorning.netvideo.dao;

import cn.earlymorning.netvideo.beans.Video;

import java.util.List;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_video
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_video
     *
     * @mbg.generated
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_video
     *
     * @mbg.generated
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_video
     *
     * @mbg.generated
     */
    Video selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Video record);

    List<Video> getVideoByCourseId(Integer courseId);


}