package cn.earlymorning.netvideo.beans;

import java.sql.Timestamp;


public class CourseComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course_comment.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course_comment.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course_comment.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course_comment.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course_comment.create_date
     *
     * @mbg.generated
     */
    private Timestamp createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course_comment.comment_id
     *
     * @return the value of tb_course_comment.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course_comment.comment_id
     *
     * @param commentId the value for tb_course_comment.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course_comment.course_id
     *
     * @return the value of tb_course_comment.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course_comment.course_id
     *
     * @param courseId the value for tb_course_comment.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course_comment.customer_id
     *
     * @return the value of tb_course_comment.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course_comment.customer_id
     *
     * @param customerId the value for tb_course_comment.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course_comment.pid
     *
     * @return the value of tb_course_comment.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course_comment.pid
     *
     * @param pid the value for tb_course_comment.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course_comment.content
     *
     * @return the value of tb_course_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course_comment.content
     *
     * @param content the value for tb_course_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course_comment.create_date
     *
     * @return the value of tb_course_comment.create_date
     *
     * @mbg.generated
     */
    public Timestamp getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course_comment.create_date
     *
     * @param createDate the value for tb_course_comment.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }
}