package cn.earlymorning.netvideo.beans;

import java.sql.Timestamp;


/**
 * @author 63299
 * @create 2019-05-12
 */
public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.source_url
     *
     * @mbg.generated
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.course_descript
     *
     * @mbg.generated
     */
    private String courseDescript;

    private CourseType courseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.creste_id
     *
     * @mbg.generated
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.create_date
     *
     * @mbg.generated
     */
    private Timestamp createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.course_level
     *
     * @mbg.generated
     */
    private Integer courseLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.hidden
     *
     * @mbg.generated
     */
    private Integer hidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_course.video_count
     *
     * @mbg.generated
     */
    private Integer videoCount;

    private Integer learningCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.course_id
     *
     * @return the value of tb_sys_course.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.course_id
     *
     * @param courseId the value for tb_sys_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.course_name
     *
     * @return the value of tb_sys_course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.course_name
     *
     * @param courseName the value for tb_sys_course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.url
     *
     * @return the value of tb_sys_course.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.url
     *
     * @param url the value for tb_sys_course.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.source_url
     *
     * @return the value of tb_sys_course.source_url
     *
     * @mbg.generated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.source_url
     *
     * @param sourceUrl the value for tb_sys_course.source_url
     *
     * @mbg.generated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.course_descript
     *
     * @return the value of tb_sys_course.course_descript
     *
     * @mbg.generated
     */
    public String getCourseDescript() {
        return courseDescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.course_descript
     *
     * @param courseDescript the value for tb_sys_course.course_descript
     *
     * @mbg.generated
     */
    public void setCourseDescript(String courseDescript) {
        this.courseDescript = courseDescript == null ? null : courseDescript.trim();
    }

    public CourseType getCourseType() {
        return courseType;
    }

    public void setCourseType(CourseType courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.create_id
     *
     * @return the value of tb_sys_course.create_id
     *
     * @mbg.generated
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.create_id
     *
     * @param createId the value for tb_sys_course.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.create_date
     *
     * @return the value of tb_sys_course.create_date
     *
     * @mbg.generated
     */
    public Timestamp getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.create_date
     *
     * @param createDate the value for tb_sys_course.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.course_level
     *
     * @return the value of tb_sys_course.course_level
     *
     * @mbg.generated
     */
    public Integer getCourseLevel() {
        return courseLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.course_level
     *
     * @param courseLevel the value for tb_sys_course.course_level
     *
     * @mbg.generated
     */
    public void setCourseLevel(Integer courseLevel) {
        this.courseLevel = courseLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.sort
     *
     * @return the value of tb_sys_course.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.sort
     *
     * @param sort the value for tb_sys_course.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.hidden
     *
     * @return the value of tb_sys_course.hidden
     *
     * @mbg.generated
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.hidden
     *
     * @param hidden the value for tb_sys_course.hidden
     *
     * @mbg.generated
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_course.video_count
     *
     * @return the value of tb_sys_course.video_count
     *
     * @mbg.generated
     */
    public Integer getVideoCount() {
        return videoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_course.video_count
     *
     * @param videoCount the value for tb_sys_course.video_count
     *
     * @mbg.generated
     */
    public void setVideoCount(Integer videoCount) {
        this.videoCount = videoCount;
    }

    public Integer getLearningCount() {
        return learningCount;
    }

    public void setLearningCount(Integer learningCount) {
        this.learningCount = learningCount;
    }
}