package cn.earlymorning.netvideo.beans;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_member.m_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_member.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_member.deadline
     *
     * @mbg.generated
     */
    private Date deadline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_member.m_id
     *
     * @return the value of tb_sys_member.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_member.m_id
     *
     * @param mId the value for tb_sys_member.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_member.customer_id
     *
     * @return the value of tb_sys_member.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_member.customer_id
     *
     * @param customerId the value for tb_sys_member.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_member.deadline
     *
     * @return the value of tb_sys_member.deadline
     *
     * @mbg.generated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_member.deadline
     *
     * @param deadline the value for tb_sys_member.deadline
     *
     * @mbg.generated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }
}