package cn.earlymorning.netvideo.beans;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_role.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_role.role_descript
     *
     * @mbg.generated
     */
    private String roleDescript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_role.role_id
     *
     * @return the value of tb_sys_role.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_role.role_id
     *
     * @param roleId the value for tb_sys_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_role.role_name
     *
     * @return the value of tb_sys_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_role.role_name
     *
     * @param roleName the value for tb_sys_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_role.role_descript
     *
     * @return the value of tb_sys_role.role_descript
     *
     * @mbg.generated
     */
    public String getRoleDescript() {
        return roleDescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_role.role_descript
     *
     * @param roleDescript the value for tb_sys_role.role_descript
     *
     * @mbg.generated
     */
    public void setRoleDescript(String roleDescript) {
        this.roleDescript = roleDescript == null ? null : roleDescript.trim();
    }
}