package cn.earlymorning.netvideo.beans;

import java.util.Date;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.video_id
     *
     * @mbg.generated
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.video_name
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.video_level
     *
     * @mbg.generated
     */
    private Integer videoLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.hidden
     *
     * @mbg.generated
     */
    private Integer hidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.video_descript
     *
     * @mbg.generated
     */
    private String videoDescript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_video.create_customer_id
     *
     * @mbg.generated
     */
    private Integer createCustomerId;

    private String isWatched;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.video_id
     *
     * @return the value of tb_sys_video.video_id
     *
     * @mbg.generated
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.video_id
     *
     * @param videoId the value for tb_sys_video.video_id
     *
     * @mbg.generated
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.video_name
     *
     * @return the value of tb_sys_video.video_name
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.video_name
     *
     * @param videoName the value for tb_sys_video.video_name
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.course_id
     *
     * @return the value of tb_sys_video.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.course_id
     *
     * @param courseId the value for tb_sys_video.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.url
     *
     * @return the value of tb_sys_video.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.url
     *
     * @param url the value for tb_sys_video.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.video_level
     *
     * @return the value of tb_sys_video.video_level
     *
     * @mbg.generated
     */
    public Integer getVideoLevel() {
        return videoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.video_level
     *
     * @param videoLevel the value for tb_sys_video.video_level
     *
     * @mbg.generated
     */
    public void setVideoLevel(Integer videoLevel) {
        this.videoLevel = videoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.pid
     *
     * @return the value of tb_sys_video.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.pid
     *
     * @param pid the value for tb_sys_video.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.sort
     *
     * @return the value of tb_sys_video.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.sort
     *
     * @param sort the value for tb_sys_video.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.hidden
     *
     * @return the value of tb_sys_video.hidden
     *
     * @mbg.generated
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.hidden
     *
     * @param hidden the value for tb_sys_video.hidden
     *
     * @mbg.generated
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.video_descript
     *
     * @return the value of tb_sys_video.video_descript
     *
     * @mbg.generated
     */
    public String getVideoDescript() {
        return videoDescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.video_descript
     *
     * @param videoDescript the value for tb_sys_video.video_descript
     *
     * @mbg.generated
     */
    public void setVideoDescript(String videoDescript) {
        this.videoDescript = videoDescript == null ? null : videoDescript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.create_date
     *
     * @return the value of tb_sys_video.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.create_date
     *
     * @param createDate the value for tb_sys_video.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_video.create_customer_id
     *
     * @return the value of tb_sys_video.create_customer_id
     *
     * @mbg.generated
     */
    public Integer getCreateCustomerId() {
        return createCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_video.create_customer_id
     *
     * @param createCustomerId the value for tb_sys_video.create_customer_id
     *
     * @mbg.generated
     */
    public void setCreateCustomerId(Integer createCustomerId) {
        this.createCustomerId = createCustomerId;
    }

    public String getIsWatched() {
        return isWatched;
    }

    public void setIsWatched(String isWatched) {
        this.isWatched = isWatched;
    }
}